// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtz_KdjlEpNiNAKxJOUu0o9lFjwNYwstw',
    appId: '1:728374566977:web:a9b8fe2ba6184a2e7c66c0',
    messagingSenderId: '728374566977',
    projectId: 'ai-alarm',
    authDomain: 'ai-alarm.firebaseapp.com',
    storageBucket: 'ai-alarm.appspot.com',
    measurementId: 'G-EDG8W7MJPQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7Zjhooxbjw0qn5nZCnKPNX9GO0mpg0Nw',
    appId: '1:728374566977:android:1943013411f40f537c66c0',
    messagingSenderId: '728374566977',
    projectId: 'ai-alarm',
    storageBucket: 'ai-alarm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2bo3XqiOUmTnnvklSD3Qi1unI5ciTedA',
    appId: '1:728374566977:ios:9f490a662234a9637c66c0',
    messagingSenderId: '728374566977',
    projectId: 'ai-alarm',
    storageBucket: 'ai-alarm.appspot.com',
    iosBundleId: 'com.example.aiAlarm',
  );
}
